version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    deploy:
      replicas: 3
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  frontend:
    image: tomrwhite/frontend-image:latest
    build: ./frontend
    deploy:
      replicas: 3
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    container_name: project-stack_frontend
  backend:
    image: tomrwhite/backend-image:latest
    build: ./backend
    deploy:
      replicas: 3
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    container_name: project-stack_backend
    environment:
      DATABASE_URI: ${DB_URI}
      SECRET_KEY: ${SECR_KEY}
